apiVersion: batch/v1
kind: Job
metadata:
  name: ollama-pull-models
spec:
  template:
    spec:
      containers:
      - name: ollama-pull
        image: docker.io/ollama/ollama:latest
        env:
        - name: OLLAMA_HOST
          value: "http://ollama:11434"
        command: ["/bin/sh", "-c"]
        args: ["while ! ollama list >/dev/null 2>&1; do sleep 1; done; ollama pull llama3.2-vision && ollama pull nomic-embed-text"]
      restartPolicy: OnFailure
